mybatis:
  mapper-locations: mapping/*.xml
  type-aliases-package: com.haooon.serviceuser.entity
server:
  port: 8763
spring:
  redis:
    database: 0
    password: 1413141352765276
    port: 6379
    host: 114.116.120.165
    ssl: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 14135276
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://114.116.120.165:30306/test_ecds?characterEncoding=utf-8
  application:
    name: service-sys
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/