mybatis:
  mapper-locations: mapping/*.xml
  type-aliases-package: com.haooon.serviceuser.entity
server:
  port: 8762
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 9000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 14135276
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://114.116.120.165:30306/test_ecds?characterEncoding=utf-8
  application:
    name: service-user
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/