mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.haooon.serviceuser.entity
server:
  port: 8762
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 14135276
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://114.116.120.165:30306/test_ecds?characterEncoding=utf-8
  application:
    name: service-test
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/