spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        healthCheckUrl: http://${spring.cloud.consul.host}:${server.port}/actuator/health
        healthCheckInterval: 15s
        instance-id: consul-miya
  application:
    name: consul-miya
server:
  port: 8502